% GET_TU_TN
%
% Funkcia na vypocet parametrov Tu a Tn pre prenos systemu podla Strjcovej identifikacie

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


function [Tu,Tn] = get_tu_tn(n,K,T,D,gui,ptv_str_lang,fgcolor)

% Tabulka pre strejcovu identifikaciu
tab = ptf_strejc_table;

if(n==1)
    Tn = T;
    Tu = D;

elseif(n<=8)
    Tn = T/tab(2,n);
    Tu = (D/Tn + tab(1,n))*Tn;

else
    disp(' Zadali ste privysoky rad! 1 < n < 9')
end


%-------- GUI -----------%
if(gui==1)

close(findobj('Tag','ptt_tutn'))

    fig3 = figure('Color','blue',...
          'Tag','ptt_tutn',...
          'Resize','off',...
          'Menubar','none',...
          'Numbertitle','off',...
          'name',ptg_string(1,7,ptv_str_lang), ...
          'position',[100 100 220 150]);
                
       text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 95 80 25],...
          'String','Tu = ');
       text =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Tu),...
          'Position',[112 95 80 25],...
          'CallBack','set(gco,''String'',Tu)');

      text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 55 80 25],...
          'String','Tn = ');
       text =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Tn),...
          'Position',[112 55 80 25],...
          'CallBack','set(gco,''String'',Tn)');
      
    potvrdenie = uicontrol(gcf,...
          'Style','push',...
          'Position',[60 15 100 25],...
          'Fontsize',[11],...
          'Fontweight','bold',...          
          'String',ptg_string(3,1,ptv_str_lang),...
          'ForegroundColor','black',...
          'CallBack','close');
  end