% GET_TU_TN
%
% Funkcia na vypocet parametrov Tu a Tn pre prenos systemu podla Strjcovej identifikacie



function [Tu,Tn] = get_tu_tn(n,K,T,D,gui,ptv_str_lang,fgcolor)

% Tabulka pre strejcovu identifikaciu
tab = ptf_strejc_table;

if(n==1)
    Tn = T;
    Tu = D;

elseif(n<=8)
    Tn = T/tab(2,n);
    Tu = (D/Tn + tab(1,n))*Tn;

else
    disp(' Zadali ste privysoky rad! 1 < n < 9')
end


%-------- GUI -----------%
if(gui==1)

close(findobj('Tag','ptt_tutn'))

    fig3 = figure('Color','blue',...
          'Tag','ptt_tutn',...
          'Resize','off',...
          'Menubar','none',...
          'Numbertitle','off',...
          'name',ptg_string(1,7,ptv_str_lang), ...
          'position',[100 100 220 150]);
                
       text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 95 80 25],...
          'String','Tu = ');
       text =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Tu),...
          'Position',[112 95 80 25],...
          'CallBack','set(gco,''String'',Tu)');

      text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 55 80 25],...
          'String','Tn = ');
       text =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Tn),...
          'Position',[112 55 80 25],...
          'CallBack','set(gco,''String'',Tn)');
      
    potvrdenie = uicontrol(gcf,...
          'Style','push',...
          'Position',[60 15 100 25],...
          'Fontsize',[11],...
          'Fontweight','bold',...          
          'String',ptg_string(3,1,ptv_str_lang),...
          'ForegroundColor','black',...
          'CallBack','close');
  end