
% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------

function pth_fig = mup_info(style_s0,s0,fgcolor,ptv_str_lang,ptv_cfbcg)
    
    close(findobj('Tag','ptt_error'))

if (style_s0 == 1) % Stable pole
    num = 28;
    naspat = '';
    color = 'blue';
    name = ptg_string(1,7,ptv_str_lang);

else            % Unstable pole
    num = 27;
    naspat = ',reg_v';
    color = 'red';
    name = ptg_string(1,6,ptv_str_lang);
end

    pth_fig = figure('Color',color,...
          'Resize','off',...
          'Numbertitle','off',...
          'Tag','ptt_error',...
          'Menubar','none',...
          'name',name, ...
          'position',[100 100 260 100]);

    % Clolourful effect
    ptv_cfbcg = get(findobj('Tag','pt'),'UserData');
    if(isempty(ptv_cfbcg)==1)
        ptv_cfbcg = 0;
    end

    if((ptv_cfbcg==1)&&(style_s0==2))
        ptf_cfbcg(gcf,2);
    else
        ptf_cfbcg(gcf,ptv_cfbcg);
    end 
      
    navrh_text= uicontrol(gcf,...
          'Style','text',...
          'position',[15 10 235 80],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptg_string(11,num,ptv_str_lang));

    s0_t =  uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'Fontweight','bold',...          
          'BackgroundColor',[1 1 1],... 	
          'HorizontalAlignment','center',...         
          'Position',[40 45 100 23],...
          'String',ptg_string(11,26,ptv_str_lang));

    s0_t =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(s0),...
          'Position',[120 45 100 25],...
          'CallBack','set(gco,''String'',num2str(s0))'); 

    porucha = uicontrol(gcf,...
          'Style','push',...
          'Position',[85 15 90 25],...
          'Fontsize',[11],...
          'String',ptg_string(3,1,ptv_str_lang),...
          'Fontweight','bold',...
          'ForegroundColor','red',...
          'CallBack',['close',naspat]);

