% NA_MODEL4
%
% Volany z NA_MODEL na doplnenie vstupov, pre premennu TYP_ID==3
% Zadaju sa parametre tlmene kmitaveho systemu regulovaneho modelu
%
% Vrati sa spat do NA_MODEL



QK=K;
QT_km=T_km;
Qksi_km=ksi_km;
QD_km=D_km;
Qcas_simulacie =cas_simulacie;

%----- PREKRYTIE POVODNYCH VSTUPOV -----%
Qtext =  uicontrol(gcf,...
          'Style','text',...
          'BackgroundColor',get(gcf,'Color'),... 
          'Position',[20 80 240 145]);
  
%------------------------------- K_km ----------------------------------------          
          
       QK_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 195 80 25],...
          'String',ptg_string(8,2,ptv_str_lang));
      
       HK =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QK) ,...
          'Position',[102 195 80 25],...
          'CallBack',['QK=str2num(get(gco,''String''));']);
 
          
 %------------------------------- T_km ---------------------------------------         
          
       QT_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 160 80 25],...
          'String',ptg_string(8,7,ptv_str_lang));
      
       HT =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QT_km),...
          'Position',[102 160 80 25],...
          'CallBack',['QT_km=str2num(get(gco,''String''));']);              

%----------------------------- ksi_km ------------------------------------------                   
                    
       Qksi_km_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 125 80 25],...
          'String',ptg_string(8,8,ptv_str_lang));
      
       Hksi_km =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qksi_km),...
          'Position',[102 125 80 25],...
          'CallBack',['Qksi_km=str2num(get(gco,''String''));']);      
 %------------------------------ D_km ----------------------------------------         
               
       QD_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...	
          'Position',[20 90 80 25],...
          'String',ptg_string(8,9,ptv_str_lang));
      
       HD =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QD_km),...
          'Position',[102 90 80 25],...
          'CallBack',['QD_km=str2num(get(gco,''String''));']);