% NA_MODEL2
%
% Volany z NA_MODEL na doplnenie vstupov, pre premennu TYP_ID==1
% Zadaju sa parametre vseobecneho prenosu regulovaneho modelu
%
% Vrati sa spat do NA_MODEL

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


Qcit=cit;
Qmen=men;
QD=D;
Qcas_simulacie =cas_simulacie;

% ic je vektor na kontrolu zadania vstupov
ic=zeros(1,4);
     
%----- PREKRYTIE POVODNYCH VSTUPOV -----%
Qtext =  uicontrol(gcf,...
          'Style','text',...
          'BackgroundColor',get(gcf,'Color'),... 
          'Position',[20 80 240 145]);
      
%----------------------------- cit ------------------------------------------                   
                    
       Qcit_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 195 60 25],...
          'String',ptg_string(8,14,ptv_str_lang));      
       Qcit =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qcit),...
          'Position',[80 195 180 25],...
          'CallBack',['ic(1,1)=1;Qcit=str2num(get(gco,''String''));']);
      
%------------------------------- men ----------------------------------------          
          
       Qmen_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 160 60 25],...
          'String',ptg_string(8,15,ptv_str_lang));
      
       Qmen =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qmen) ,...
          'Position',[80 160 180 25],...
          'CallBack',['ic(1,2)=1;Qmen=str2num(get(gco,''String''));']);
 
 %------------------------------ D ----------------------------------------         
               
       QD_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...	
          'Position',[20 125 60 25],...
          'String',ptg_string(8,4,ptv_str_lang));
      
       QD =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QD),...
          'Position',[80 125 180 25],...
          'CallBack',['ic(1,3)=1;QD=str2num(get(gco,''String''));']);
      
%--- KMITAVA IDENTIFIKCIA ---------
if(typ_i>1)
    typ_i =1;
end

QKM=uicontrol(gcf,'Tag','KM',...
    'Style','Check','Units','Pixels','Position',[20 90 240 25],...
    'ForegroundColor','Black',...
    'BackgroundColor',fgcolor,...  
    'Fontweight','bold',...
    'String',ptg_string(5,3,ptv_str_lang),...
    'Value',typ_i,...
    'Callback','typ_i = get(gco,''Value'');');