% P_PARAM
%
%   Sluzi na vypocet parametrov P regulatora pomocou vybranej experimentalnej
%   metody



% METODY
%
% ZIEGLER-NICHOLS

if typy_ns==1 

z_r =((1/K)*(Tn/Tu));

t_i=1e10;
t_d=0;
close
simul_param

% STREJC

elseif typy_ns==2 

    % Testovanie vhodnosti radu, aby sa predislo deleniu nulou
    if (n<2)
        pth_fig = ptg_error('reg_v',ptg_string(11,9,ptv_str_lang),ptv_str_lang);
    else
        z_r =(1/K)*(1/(n-1));

        t_i=1e10;
        t_d=0;
        close
        simul_param
    end

% COHEN-COON

elseif typy_ns==3 
               
z_r =(1/K)*(Tn/Tu)*(1+((1/3)*(Tu/Tn)));

t_i=1e10;
t_d=0;
close
simul_param
  
% CHIEN,HRONES,RESWICK (0% PREREG.)

           elseif typy_ns==4
               
    figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[120 200 360 150]);
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 100 300 30],...
          'String',ptg_string(11,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,z_r =0.3*(Tn/(K*Tu));t_i=1e10;t_d=0;simul_param');
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 60 300 30],...
          'String',ptg_string(11,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,z_r =0.3*(Tn/(K*Tu));t_i=1e10;t_d=0;simul_param');
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 60 30],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');

% CHIEN,HRONES,RESWICK (20% PREREG.)

elseif typy_ns==5

    figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[120 200 360 150]);
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 100 300 30],...
          'String',ptg_string(11,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,z_r =0.7*(Tn/(K*Tu));t_i=1e10;t_d=0;simul_param');
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 60 300 30],...
          'String',ptg_string(11,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,z_r =0.7*(Tn/(K*Tu));t_i=1e10;t_d=0;simul_param');
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 60 30],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');

% ITAE METHOD (ODSTRANENIE VPLYVU PORUCHY)
%
elseif typy_ns == 6

    [z_r, t_i, t_d] = pte_itaem(1,K,Tu,Tn,2);
    close
    simul_param
        

% LOPEZ IAE-ISE METHOD
%
elseif typy_ns == 7

    [z_r,t_i,t_d] = pte_iaeisem(1,K,Tu,Tn);
    close
    simul_param

% ------------------- %
%
end