% PARAM_VL3
% Zadanie parametrov Strejcovho prenosu
% Volane z - PARAM_VL2, aj sa tam vrati

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


Qn =n;
QK =K;
QT =T;
QD =D;

%----------------------------- n ------------------------------------------                   
                    
HT1 = uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 190 80 25],...
          'String',ptg_string(8,1,ptv_str_lang));
      
HB1 = uicontrol(gcf,...
          'Tag','ptt_n',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qn),...
          'Position',[102 190 80 25],...
          'CallBack',['ic(1,1)=1;Qn=str2num(get(gco,''String''));']);
      

%------------------------------- K ----------------------------------------          
          
HT2 = uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 155 80 25],...
          'String',ptg_string(8,2,ptv_str_lang));
      
HB2 = uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Tag','ptt_K',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QK) ,...
          'Position',[102 155 80 25],...
          'CallBack',['ic(1,2)=1;QK=str2num(get(gco,''String''));']);

%------------------------------- T ---------------------------------------         
          
HT3 = uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 120 80 25],...
          'String',ptg_string(8,3,ptv_str_lang));
      
HB3 = uicontrol(gcf,...
          'Tag','ptt_T',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QT),...
          'Position',[102 120 80 25],...
          'CallBack',['ic(1,3)=1;QT=str2num(get(gco,''String''));']);              

 %------------------------------ D ----------------------------------------         
               
HT4 = uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...	
          'Position',[20 85 80 25],...
          'String',ptg_string(8,4,ptv_str_lang));
      
HB4 = uicontrol(gcf,...
          'Tag','ptt_D',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QD),...
          'Position',[102 85 80 25],...
          'CallBack',['ic(1,4)=1;QD=str2num(get(gco,''String''));']);
