% PARAM_VL4
% Zadanie parametrov Strejcovho prenosu
% Volane z - PARAM_VL2, aj sa tam vrati



QK=K;
QT_km=T_km;
Qksi_km=ksi_km;
QD_km=D_km;

%------------------------------- K_km ----------------------------------------          
          
       QK_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 190 80 25],...
          'String',ptg_string(8,2,ptv_str_lang));
      
       HK =  uicontrol(gcf,...
          'Tag','ptt_K',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QK) ,...
          'Position',[102 190 80 25],...
          'CallBack',['QK=str2num(get(gco,''String''));']);
 
          
 %------------------------------- T_km ---------------------------------------         
          
       QT_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 155 80 25],...
          'String',ptg_string(8,7,ptv_str_lang));
      
       HT =  uicontrol(gcf,...
          'Tag','ptt_T_km',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QT_km),...
          'Position',[102 155 80 25],...
          'CallBack',['QT_km=str2num(get(gco,''String''));']);              

%----------------------------- ksi_km ------------------------------------------                   
                    
       Qksi_km_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 120 80 25],...
          'String',ptg_string(8,8,ptv_str_lang));
      
       Hksi_km =  uicontrol(gcf,...
          'Tag','ptt_ksi_km',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qksi_km),...
          'Position',[102 120 80 25],...
          'CallBack',['Qksi_km=str2num(get(gco,''String''));']);      
 %------------------------------ D_km ----------------------------------------         
               
       QD_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...	
          'Position',[20 85 80 25],...
          'String',ptg_string(8,9,ptv_str_lang));
      
       HD =  uicontrol(gcf,...
          'Tag','ptt_D_km',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QD_km),...
          'Position',[102 85 80 25],...
          'CallBack',['QD_km=str2num(get(gco,''String''));']);