% PARAM_VL3
% Zadanie parametrov Strejcovho prenosu
% Volane z - PARAM_VL2, aj sa tam vrati



Qn =n;
QK =K;
QT =T;
QD =D;

%----------------------------- n ------------------------------------------                   
                    
HT1 = uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 190 80 25],...
          'String',ptg_string(8,1,ptv_str_lang));
      
HB1 = uicontrol(gcf,...
          'Tag','ptt_n',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qn),...
          'Position',[102 190 80 25],...
          'CallBack',['ic(1,1)=1;Qn=str2num(get(gco,''String''));']);
      

%------------------------------- K ----------------------------------------          
          
HT2 = uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 155 80 25],...
          'String',ptg_string(8,2,ptv_str_lang));
      
HB2 = uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Tag','ptt_K',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QK) ,...
          'Position',[102 155 80 25],...
          'CallBack',['ic(1,2)=1;QK=str2num(get(gco,''String''));']);

%------------------------------- T ---------------------------------------         
          
HT3 = uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 120 80 25],...
          'String',ptg_string(8,3,ptv_str_lang));
      
HB3 = uicontrol(gcf,...
          'Tag','ptt_T',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QT),...
          'Position',[102 120 80 25],...
          'CallBack',['ic(1,3)=1;QT=str2num(get(gco,''String''));']);              

 %------------------------------ D ----------------------------------------         
               
HT4 = uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...	
          'Position',[20 85 80 25],...
          'String',ptg_string(8,4,ptv_str_lang));
      
HB4 = uicontrol(gcf,...
          'Tag','ptt_D',...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QD),...
          'Position',[102 85 80 25],...
          'CallBack',['ic(1,4)=1;QD=str2num(get(gco,''String''));']);
