% PI_PARAM
%
%   Sluzi na vypocet parametrov PI regulatora pomocou vybranej experimentalnej
%   metody

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


% METODY:
%
%-----------------------------------------------
%
% ZIEGLER-NICHOLS
if typy_ns==1
    
    
z_r =((0.9/K)*(Tn/Tu));
t_i=(3.33*Tu);

t_d=0;
close
simul_param;
          
%-------------------------------------------------------------------------
% STREJC
elseif typy_ns==2 
    
    % Testovanie vhodnosti radu, aby sa predislo deleniu nulou
    if (n<2)
        pth_fig = ptg_error('reg_v',ptg_string(11,9,ptv_str_lang),ptv_str_lang);
    else

       z_r =(1/K)*((n+2)/(4*(n-1)));
       t_i =T*((n+2)/3);

t_d=0;
close
simul_param
end
          
%-----------------------------------------------------------------------          
% COHEN-COON
elseif typy_ns==3
 
   z_r =(1/K)*(Tn/Tu)*(0.9+((1/12)*(Tu/Tn)));
   t_i =Tu*((30+3*(Tu/Tn))/(9+20*(Tu/Tn)));

t_d=0;
close
simul_param
  
%--------------------------------------------------------------------------          
% METODA PRIAMEJ SYNTEZY REGULATORA 
elseif typy_ns==4

% Pomocna premenna ic3 pre kontrolu zadania Turo
ic3=zeros(1,1);
% Pomocna premenna ic4 pre kontrolu spravneho zadania Turo
ic4=0;
QTuro='???';

% close

 fig = figure('Color','blue',...
          'Resize','off',...
          'Menubar',ptv_fig_menubar,...
          'Numbertitle','off',...
          'name',ptg_string(1,2,ptv_str_lang), ...
          'position',[100 200 215 200]);   
       navrh_text= uicontrol(gcf,...
          'Style','text',...
          'position',[15 85 185 105],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptg_string(11,11,ptv_str_lang));
       Turo_text= uicontrol(gcf,...
          'Style','text',...
          'position',[15 50 90 25],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptg_string(11,12,ptv_str_lang));
       QTuro =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QTuro),...
          'Position',[108 50 90 25],...
          'CallBack',['QTuro=str2num(get(gco,''String''));ic3(1,1)=1;']); 
    %------------------------------- Tn ---------------------------------------         
    Tn_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[20 100 85 25],...
          'String',ptg_string(8,6,ptv_str_lang));
    Tn_text2 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[108 100 85 25],...
          'String',num2str(Tn));
    %----SPAT-----%
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[15 15 60 25],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');
    potvrdenie = uicontrol(gcf,...
          'Style','push',...
          'Position',[100 15 100 25],...
          'Fontweight','bold',...
          'String',ptg_string(3,1,ptv_str_lang),...
          'Fontsize',[11],...
          'ForegroundColor','red',...
          'CallBack','close,naspat=''pi_param'';testturo;if(ic4==1),z_r =(Tn/(K*(Turo+D)));t_i =Tn;t_d=0;simul_param,end');

%--------------------------------------------------------------------------
% HAALMAN
elseif typy_ns==5         
         
    z_r =((2*Tn)/(3*K*Tu));
    t_i =Tn;

t_d=0;
close
  simul_param
         
          
%--------------------------------------------------------------------------          
% CHIEN,HRONES,RESWICK (0% PREREGULOVANIE)
elseif typy_ns==6

    figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[120 200 360 150]);
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 100 300 30],...
          'String',ptg_string(11,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,z_r =(0.35*Tn)/(K*Tu); t_i =1.17*Tn;t_d=0;simul_param');
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 60 300 30],...
          'String',ptg_string(11,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,z_r =(0.6*Tn)/(K*Tu); t_i =(0.8*Tu+0.5*Tn);t_d=0;simul_param');
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 60 30],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');
  
%--------------------------------------------------------------------------          
% CHIEN,HRONES,RESWICK (20% PREREGULOVANIE)
elseif typy_ns==7

    figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[120 200 360 150]);
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 100 300 30],...
          'String',ptg_string(11,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,z_r =(0.6*Tn)/(K*Tu);t_i =Tn;t_d=0;simul_param');
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 60 300 30],...
          'String',ptg_string(11,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,z_r =(0.7*Tn)/(K*Tu);t_i =(Tu+0.3*Tn);t_d=0;simul_param');
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 60 30],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');
   
%-----------------------------------------------
%
% HALF DAMPPING METHOD

elseif typy_ns == 8

    [z_r, t_i, t_d] = pte_hdm(2,K,Tu,Tn);

close
simul_param;

%--------------------------------------------------------------------------          
% RIVERA,MORARI  

elseif typy_ns==9
close
% Pomocna premenna ic3 pre kontrolu zadania Turo
ic3=zeros(1,1);
% Pomocna premenna ic4 pre kontrolu spravneho zadania Turo
ic4=0;
QTuro='???';

  fig = figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'position',[100 200 215 255]);   
       navrh_text= uicontrol(gcf,...
          'Style','text',...
          'position',[15 85 185 155],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptg_string(11,15,ptv_str_lang));
       Turo_text= uicontrol(gcf,...
          'Style','text',...
          'position',[15 50 90 25],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptg_string(11,12,ptv_str_lang));
       QTuro =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QTuro),...
          'Position',[108 50 90 25],...
          'CallBack',['QTuro=str2num(get(gco,''String''));ic3(1,1)=1;']); 
       %------------------------------- Tn ---------------------------------------         
    Tn_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[20 130 85 25],...
          'String',ptg_string(8,6,ptv_str_lang));
    Tn_text2 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[108 130 85 25],...
          'String',num2str(Tn));
       %------------------------------- Tu ---------------------------------------         
    Tu_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[20 100 85 25],...
          'String',ptg_string(8,5,ptv_str_lang));
    Tu_text2 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[108 100 85 25],...
          'String',num2str(Tu));      
    %----SPAT-----%
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[15 15 60 25],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');
    potvrdenie = uicontrol(gcf,...
          'Style','push',...
          'Position',[100 15 100 25],...
          'Fontweight','bold',...
          'String',ptg_string(3,1,ptv_str_lang),...
          'Fontsize',[11],...
          'ForegroundColor','red',...
          'CallBack','close,naspat=''pi_param'';testturo;if(ic4==1),z_r =(Tn/(K*Turo)); t_i =Tn;t_d=0;simul_param,end');

%--------------------------------------------------------------------------          
% RIVERA,MORARI (SPRESNENY)

elseif typy_ns==10
close

% Pomocna premenna ic3 pre kontrolu zadania Turo
ic3=zeros(1,1);
% Pomocna premenna ic4 pre kontrolu spravneho zadania Turo
ic4=0;
QTuro='???';

     fig = figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'position',[100 200 215 255]);   
       navrh_text= uicontrol(gcf,...
          'Style','text',...
          'position',[15 85 185 155],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptg_string(11,15,ptv_str_lang));
       Turo_text= uicontrol(gcf,...
          'Style','text',...
          'position',[15 50 90 25],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptg_string(11,12,ptv_str_lang));
       QTuro =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QTuro),...
          'Position',[108 50 90 25],...
          'CallBack',['QTuro=str2num(get(gco,''String''));ic3(1,1)=1;']); 
    %------------------------------- Tn ---------------------------------------         
    Tn_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[20 130 85 25],...
          'String',ptg_string(8,6,ptv_str_lang));
    Tn_text2 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[108 130 85 25],...
          'String',num2str(Tn));
       %------------------------------- Tu ---------------------------------------         
    Tu_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[20 100 85 25],...
          'String',ptg_string(8,5,ptv_str_lang));
    Tu_text2 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','white',... 	
          'Position',[108 100 85 25],...
          'String',num2str(Tu));      
    %----SPAT-----%
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[15 15 60 25],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');
    potvrdenie = uicontrol(gcf,...
          'Style','push',...
          'Position',[100 15 100 25],...
          'Fontweight','bold',...
          'String',ptg_string(3,1,ptv_str_lang),...
          'Fontsize',[11],...
          'ForegroundColor','red',...
          'CallBack','close,testturo;if(ic4==1),z_r =((2*Tn)+Tu)/(2*K*Turo);t_i =Tn+(Tu/2);t_d=0;simul_param,end');

% ----------------------------------------- %
%
% ASTROM - HAGGLUND METHOD, Ms = 1.4

elseif typy_ns == 11

    if(Tu <= 0)
        pth_fig = ptg_error('reg_v',ptg_string(11,44,ptv_str_lang),ptv_str_lang);

    else
        [z_r,t_i,t_d,b_w] = pte_ahm(2,K,Tu,Tn,1.4);
        close
        simul_param;
    end

% ----------------------------------------- %
%
% ASTROM - HAGGLUND METHOD, Ms = 2.0

elseif typy_ns == 12

    if(Tu <= 0)
        pth_fig = ptg_error('reg_v',ptg_string(11,44,ptv_str_lang),ptv_str_lang);

    else
        [z_r,t_i,t_d,b_w] = pte_ahm(2,K,Tu,Tn,2);
        close
        simul_param;
    end
%-----------------------------------------------
%
% ISE METHOD

elseif typy_ns == 13
    
    figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[120 200 360 150]);
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 100 300 30],...
          'String',ptg_string(11,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,[z_r, t_i, t_d] = pte_opcm(2,K,Tu,Tn,1,1);simul_param');
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 60 300 30],...
          'String',ptg_string(11,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,[z_r, t_i, t_d] = pte_opcm(2,K,Tu,Tn,2,1);simul_param');
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 60 30],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');
%-----------------------------------------------
%
% ITSE METHOD

elseif typy_ns == 14
    
    figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[120 200 360 150]);
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 100 300 30],...
          'String',ptg_string(11,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,[z_r, t_i, t_d] = pte_opcm(2,K,Tu,Tn,1,2);simul_param');
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 60 300 30],...
          'String',ptg_string(11,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,[z_r, t_i, t_d] = pte_opcm(2,K,Tu,Tn,2,2);simul_param');
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 60 30],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');

%-----------------------------------------------
%
% ISTSE METHOD

elseif typy_ns == 15
    
    figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[120 200 360 150]);
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 100 300 30],...
          'String',ptg_string(11,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,[z_r, t_i, t_d] = pte_opcm(2,K,Tu,Tn,1,3);simul_param');
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 60 300 30],...
          'String',ptg_string(11,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,[z_r, t_i, t_d] = pte_opcm(2,K,Tu,Tn,2,3);simul_param');
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 60 30],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');

% ----------------------------------------- %
%
% IAE METHOD

elseif typy_ns == 16

    [z_r, t_i, t_d] = pte_iaem(2,K,Tu,Tn);

close
simul_param;

% ----------------------------------------- %
%
% ITAE METHOD

elseif typy_ns == 17
    
    figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[120 200 360 150]);
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 100 300 30],...
          'String',ptg_string(11,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,[z_r, t_i, t_d] = pte_itaem(2,K,Tu,Tn,1);simul_param');
    sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[30 60 300 30],...
          'String',ptg_string(11,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,[z_r, t_i, t_d] = pte_itaem(2,K,Tu,Tn,2);simul_param');
    navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 60 30],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,reg_v');

% ----------------------------------------- %
%
% LOPEZ IAE-ISE METHOD

elseif typy_ns == 18

    [z_r,t_i,t_d] = pte_iaeisem(2,K,Tu,Tn);

close
simul_param;

% ----------------------------------------- %
%
% LIPTAK METHOD

elseif typy_ns == 19

    [z_r,t_i,t_d] = pte_lip(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% St.CLAIR METHOD

elseif typy_ns == 20

    [z_r,t_i,t_d] = pte_stc(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% SHINKEY METHOD

elseif typy_ns == 21

    [z_r,t_i,t_d] = pte_shi(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% McMILLAN METHOD

elseif typy_ns == 22

    [z_r,t_i,t_d] = pte_mcm(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% HAZENBROEK AND VAN DER WAERDEN METHOD

elseif typy_ns == 23

    [z_r,t_i,t_d] = pte_hvw(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% FERTIK AND SHARPE METHOD

elseif typy_ns == 24

    [z_r,t_i,t_d] = pte_fsh(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% PARR METHOD

elseif typy_ns == 25

    [z_r,t_i,t_d] = pte_par(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% KLEIN ET AL. METHOD

elseif typy_ns == 26

    [z_r,t_i,t_d] = pte_kle(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% BORRESEN AND GRINDAL METHOD

elseif typy_ns == 27

    [z_r,t_i,t_d] = pte_bgr(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% ZIEGLER-NICHOLS IMPROVED

elseif typy_ns == 28

    [z_r,t_i,t_d] = pte_zni(2,2,K,Tn,Tu);

close
simul_param;

% ----------------------------------------- %
%
% ZIEGLER-NICHOLS ULITIMATE CYCLE METHOD

elseif typy_ns == 29

    [z_r,t_i,t_d] = pte_znu(2,2,K,Tn,Tu);

close
simul_param;
%
% ----------------------------------------- %
%
% SUYAMA

elseif typy_ns == 30

    [z_r,t_i,t_d] = pte_suy(2,2,K,Tn,Tu);

close
simul_param;
%
% ----------------------------------------- %
%
% KUHN T-SUM METHOD
%
elseif typy_ns == 31

    [z_r,t_i,t_d] = pte_tsm(2,2,n,K,T);

close
simul_param;
% ----------------------------------------- %

end