% POROV2
%
% Volany z POROVNAT na doplnenie vstupov, pre premennu TYP_ID==1
% Zadaju sa parametre vseobecneho prenosu regulovaneho modelu
%
% Vrati sa spat do POROVNAT



Qcit=cit;
Qmen=men;
QD=D;
Qcas_simulacie =cas_simulacie;

%----- PREKRYTIE POVODNYCH VSTUPOV -----%
Qtext =  uicontrol(gcf,...
          'Style','text',...
          'BackgroundColor',get(gcf,'Color'),... 
          'Position',[20 80 240 145]);
      
%----------------------------- cit ------------------------------------------                   
                    
       Qcit_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 195 60 25],...
          'String',ptg_string(8,14,ptv_str_lang));      
       Hcit =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qcit),...
          'Position',[80 195 180 25],...
          'CallBack',['Qcit=str2num(get(gco,''String''));']);
      
%------------------------------- men ----------------------------------------          
          
       Qmen_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 160 60 25],...
          'String',ptg_string(8,15,ptv_str_lang));
      
       Hmen =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qmen) ,...
          'Position',[80 160 180 25],...
          'CallBack',['Qmen=str2num(get(gco,''String''));']);
 
 %------------------------------ D ----------------------------------------         
               
       QD_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...	
          'Position',[20 125 60 25],...
          'String',ptg_string(8,4,ptv_str_lang));
      
       HD =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QD),...
          'Position',[80 125 180 25],...
          'CallBack',['QD=str2num(get(gco,''String''));']);