% PTG_ERROR

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


function pth_fig = ptg_error(ptv_error_callback,ptv_str,ptv_str_lang)

close(findobj('Tag','ptt_error'))

    pth_fig = figure('Color','red',...
          'Resize','off',...
          'Numbertitle','off',...
          'Tag','ptt_error',...
          'Menubar','none',...
          'name',ptg_string(1,6,ptv_str_lang), ...
          'position',[100 100 260 150]);

    % Clolourful effect
    ptv_cfbcg = get(findobj('Tag','pt'),'UserData');
    if(ptv_cfbcg==1)
        ptf_cfbcg(gcf,2)
    end

    pth_text = uicontrol(gcf,...
          'Style','text',...
          'position',[15 10 235 130],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[.7 .7 .7],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptv_str);
      
    pth_fig = uicontrol(gcf,...
          'Style','push',...
          'Position',[85 15 90 25],...
          'Fontsize',11,...
          'String',ptg_string(3,1,ptv_str_lang),...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack',['close,',ptv_error_callback]);