% PTG_INTKRIT
%


t = ptv_intkrit(:,1);
e = ptv_intkrit(:,2);
u = ptv_intkrit(:,3);
w = ptv_intkrit(:,4);

Qe = R;
Qu = A;
Qdu = B;

[ise,iae,ise_t,ise_de,ise_u,ise_du] = ptf_intkrit(t,e,u,w,Qe,Qu,Qdu);

% Semafor pre kvalitu regulacie:
if((iae/cas_simulacie)<0.1)
    c1='green';
elseif((iae/cas_simulacie)<0.2)
    c1='yellow';
else
    c1=[1 0.3 0.2];
 end
 
 if((ise/cas_simulacie)<0.1)
    c2='green';
elseif((ise/cas_simulacie)<0.2)
    c2='yellow';
else
    c2=[1 0.3 0.2];
 end

if((ise_t/cas_simulacie)<0.1)
    c3='green';
elseif((ise_t/cas_simulacie)<0.2)
    c3='yellow';
else
    c3=[1 0.3 0.2];
 end

 if((ise_u/cas_simulacie)<0.1)
    c4='green';
elseif((ise_u/cas_simulacie)<0.2)
    c4='yellow';
else
    c4=[1 0.3 0.2];
end

if((ise_du/cas_simulacie)<1)
    c5='green';
elseif((ise_du/cas_simulacie)<1.5)
    c5='yellow';
else
    c5=[1 0.3 0.2];
end

if((ise_de/cas_simulacie)<0.1)
    c6='green';
elseif((ise_de/cas_simulacie)<0.2)
    c6='yellow';
else
    c6=[1 0.3 0.2];
end

 fig3 = figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Tag','ptt_param',...
          'Menubar',ptv_fig_menubar,...
          'name',ptg_string(1,10,ptv_str_lang), ...
          'position',[400 200 260 300]);

% Clolourful effect
ptf_cfbcg(gcf,ptv_cfbcg)

       % IAE
       iae_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',c1,... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 255 80 25],...
          'String',ptg_string(8,41,ptv_str_lang));
       iaet =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(iae),...
          'Position',[112 255 130 25],...
          'CallBack','set(gco,''String'',num2str(iae))');

      % ISE              
       ise_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',c2,... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 215 80 25],...
          'String',ptg_string(8,42,ptv_str_lang));
       iset =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(ise),...
          'Position',[112 215 130 25],...
          'CallBack','set(gco,''String'',num2str(ise))');

      % ISE_t
       ise_t_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',c3,... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 175 80 25],...
          'String',ptg_string(8,43,ptv_str_lang));
       ise_t2 =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(ise_t),...
          'Position',[112 175 130 25],...
          'CallBack','set(gco,''String'',num2str(ise_t))');
      
       % ISE_u
       ise_u_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',c4,... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 135 80 25],...
          'String',ptg_string(8,44,ptv_str_lang));
       ise_u2 =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(ise_u),...
          'Position',[112 135 130 25],...
          'CallBack','set(gco,''String'',num2str(ise_u))');

    % ISE_du  
    ise_uu_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',c5,... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 95 80 25],...
          'String',ptg_string(8,45,ptv_str_lang));
       ise_uu2 =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(ise_du),...
          'Position',[112 95 130 25],...
          'CallBack','set(gco,''String'',num2str(ise_du))');

    % ISE_de 
    ise_e_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',c6,... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[30 55 80 25],...
          'String',ptg_string(8,46,ptv_str_lang));
       ise_e2 =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(ise_de),...
          'Position',[112 55 130 25],...
          'CallBack','set(gco,''String'',num2str(ise_de))');
            
    potvrdenie = uicontrol(gcf,...
          'Style','push',...
          'Position',[75 15 130 25],...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'CallBack','close,simul_param');

