% PTG_ERROR



function pth_fig = ptg_error(ptv_error_callback,ptv_str,ptv_str_lang)

close(findobj('Tag','ptt_error'))

    pth_fig = figure('Color','red',...
          'Resize','off',...
          'Numbertitle','off',...
          'Tag','ptt_error',...
          'Menubar','none',...
          'name',ptg_string(1,6,ptv_str_lang), ...
          'position',[100 100 260 150]);

    % Clolourful effect
    ptv_cfbcg = get(findobj('Tag','pt'),'UserData');
    if(ptv_cfbcg==1)
        ptf_cfbcg(gcf,2)
    end

    pth_text = uicontrol(gcf,...
          'Style','text',...
          'position',[15 10 235 130],...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[.7 .7 .7],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'String',ptv_str);
      
    pth_fig = uicontrol(gcf,...
          'Style','push',...
          'Position',[85 15 90 25],...
          'Fontsize',11,...
          'String',ptg_string(3,1,ptv_str_lang),...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack',['close,',ptv_error_callback]);