% REG_V
%
%   Sluzi na vyber metody syntezy PID regulatora
%
%   Dava na vyber:
%
%   SYNTEZA REGULATORA - REG_V2
%   SPAT - close



% Test, ci uz boli ziskane nejake parametre modelu regulovaneho procesu
%
if (isnumeric(n)&&isnumeric(K)&&isnumeric(T)&&isnumeric(D))||...
        (isnumeric(ksi_km)&&isnumeric(K)&&isnumeric(T_km)&&isnumeric(D_km))

   
% Premenne pre SIMULACIU, ktore sa pouziju na vypocet citatela a menovatela prenosu
% regulovaneho systemu: Gs(s)=cit/men. Najskor sa dosadzuju zadane
% premenne n,K,T,D alebo n,K,T_km,ksi_km,D_km. 
% Neskor je  v "parametroch simulacie" moznost "ZISKAT PRENOS" 
% parametre prenosu na ine hodnoty
%
if(typ_i==1) | (isnumeric(ksi_km) == 0)
    [cit,men] = get_tf(1,n,K,T);            % Strejcov model
    Dr=D;
else
    [cit,men] = get_tf(2,ksi_km,K,T_km);    % Kmitavy tvar
    Dr=D_km;
    n=2;
end


% ---------- PRACA S PRENOSOM ----------------------------------
%
% Vypocet menovatela prenosu
% Prenos v tvare: G(s)=K(s)/men(s)
% Menovatel v tvare: An*S^n + A(n-1)*S^(n-1) + ... + A1*S + A0
% a = a(end-n)*s^n + a(end-(n-1))*s^(n-1) +... + a(end-2)*s^2 + a(end-1)*s + a(end)
%
a=zeros(1,length(men));
for i=1:(length(men)-1)
    a(i)=men(end+1-i);
end
% ---------- KONIEC - PRACA S PRENOSOM --------------------------

% Vynulovanie aktualne vybranej metody
%
ptv_currmethod = 1;


fig = figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Tag','ptt_reg_v',...
          'Name',ptg_string(1,2,ptv_str_lang), ...
          'Position',[150 120 400 230]);

% % Clolourful effect
% ptf_cfbcg(gcf,ptv_cfbcg)

pth_pop1 = uicontrol(gcf,...
          'Style','popup',...
          'Tag','ptt_popup_tm',...
          'Position',[20 180 360 35],...
          'Value',ptv_currmethod,...
          'String',ptf_pop_tmlist(ptv_typpid,ptv_typtm,ptv_str_lang),...
          'ForegroundColor','black',...
          'BackGroundColor','white',...
          'CallBack','ptv_currmethod = get(gco,''Value'');');

pth_rad1 = uicontrol(gcf,...
          'Style','radio',...
          'Tag','ptt_radio_pid1',...
          'Position',[20 150 50 30],...
          'String',ptg_string(6,3,ptv_str_lang),...
          'FontWeight','bold',...
          'CallBack','ptv_typpid=ptf_pidradio(gco);ptf_pop_tmcurr(ptv_typpid,ptv_typtm,ptv_currmethod,ptv_str_lang);');

pth_rad2 = uicontrol(gcf,...
          'Style','radio',...
          'Tag','ptt_radio_pid2',...
          'Position',[20 120 50 30],...
          'String',ptg_string(6,4,ptv_str_lang),...
          'FontWeight','bold',...
          'CallBack','ptv_typpid=ptf_pidradio(gco);ptf_pop_tmcurr(ptv_typpid,ptv_typtm,ptv_currmethod,ptv_str_lang);');

pth_rad3 = uicontrol(gcf,...
          'Style','radio',...
          'Tag','ptt_radio_pid3',...
          'Position',[20 90 50 30],...
          'String',ptg_string(6,5,ptv_str_lang),...
          'FontWeight','bold',...
          'CallBack','ptv_typpid=ptf_pidradio(gco);ptf_pop_tmcurr(ptv_typpid,ptv_typtm,ptv_currmethod,ptv_str_lang);');

pth_rad4 = uicontrol(gcf,...
          'Style','radio',...
          'Tag','ptt_radio_pid4',...
          'Position',[20 60 50 30],...
          'String',ptg_string(6,6,ptv_str_lang),...
          'FontWeight','bold',...
          'CallBack','ptv_typpid=ptf_pidradio(gco);ptf_pop_tmcurr(ptv_typpid,ptv_typtm,ptv_currmethod,ptv_str_lang);');

pth_rad5 = uicontrol(gcf,...
          'Style','radio',...
          'Tag','ptt_radio_tm1',...
          'Position',[90 150 180 30],...
          'String',ptg_string(6,1,ptv_str_lang),...
          'FontWeight','bold',...
          'CallBack','ptv_typtm=ptf_tmradio(gco,typ_i,ptv_str_lang);ptf_pop_tmcurr(ptv_typpid,ptv_typtm,ptv_currmethod,ptv_str_lang);');
 
pth_rad6 = uicontrol(gcf,...
          'Style','radio',...
          'Tag','ptt_radio_tm2',...
          'Position',[90 120 180 30],...
          'String',ptg_string(6,2,ptv_str_lang),...
          'FontWeight','bold',...
          'CallBack','ptv_typtm=ptf_tmradio(gco,typ_i,ptv_str_lang);ptf_pop_tmcurr(ptv_typpid,ptv_typtm,ptv_currmethod,ptv_str_lang);');

% Controller Tuning
%
pth_but1 = uicontrol(gcf,...
          'Style','push',...
          'Position',[110 20 135 30],...
          'String',ptg_string(3,3,ptv_str_lang),...
          'ForegroundColor','black',...
          'FontWeight','bold',...
          'CallBack','close,J1=0;reg_v2');

% Back
%
pth_but2 = uicontrol(gcf,...
          'Style','push',...
          'Position',[20 20 75 30],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'FontWeight','bold',...
          'Callback','close,close(findobj(''Tag'',''ptt_tutn'')),J2=2;zatv');   

pth_text = uicontrol(gcf,...
          'Style','text',...
          'Tag','ptt_choosenpid',...
          'Position',[245 -20 155 80],...
          'BackgroundColor','blue',...
          'String','PID',...
          'ForegroundColor',[0 0 .4],...
          'FontSize',45,...
          'FontName','Tahoma',...
          'FontAngle','italic',...
          'HorizontalAlignment','right',...
          'FontWeight','bold');
      
% Preset radiobutonns
%
if(typ_i==2)
    ptv_typtm = 2;
end
%
set(findobj('Tag',['ptt_radio_pid',num2str(ptv_typpid)]),'Value',1);
set(findobj('Tag',['ptt_radio_tm',num2str(ptv_typtm)]),'Value',1);
%
% Preset text
%
ptf_choosenpid(ptv_typpid);

else
    
    % Ak neboli ziskane parametre modelu regulovaneho procesu, tak sa
    % spusti ich zadavanie
    %
    param_vl2
end