% SIMUL_PARAM
%
%   Sluzi na zadanie parametrov simulacie pre testovanie kvality navrhnuteho
%   regulatora
%
%   Spusta - TESTSIM
%   Moznost spustit - ZISKAT_GS

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


QW_povodna =W_povodna;
QW_nova =W_nova;
QW_cas_zmeny =W_cas_zmeny;

QR_povodna =R_povodna;
QR_nova =R_nova;
QR_cas_zmeny =R_cas_zmeny;

Qq_u = q_u;
Qq_du = q_du;
Qq_de = q_de;

Qpresnost_riadenia =presnost_riadenia;
Qcas_simulacie=cas_simulacie;
QU_dolne_obmedzenie =U_dolne_obmedzenie;
QU_horne_obmedzenie =U_horne_obmedzenie;

Qz_r = num2str(z_r);
Qt_i = num2str(t_i);
Qt_d = num2str(t_d);

Qt_r = num2str(t_r); % ANTI-RESET WIND UP
Qb_w = num2str(b_w);
Qt_f =  num2str(t_f); % T_D filter

Qcit=cit;
Qmen=men;
QDr=Dr;

% ic je vektor na kontrolu zadania vstupov
ic=zeros(1,22);

% Test of tuned controller
%
if(sum(z_r == '???')==3||sum(t_i == '???')==3||sum(t_d == '???')==3)
    ptv_test = 1;
else
    ptv_test = ptf_test_controller(z_r,t_i,t_d,cit(end));
end
%
if(ptv_test == 0)
    pth_fig = ptg_error('reg_v',ptg_string(9,46,ptv_str_lang),ptv_str_lang);
else

%------------------ OKNO --------------------------------------------

fig = figure('Color',[0.1020 0.4157 0.5686],... 
          'Resize','off',...
          'Numbertitle','off',...
          'name',ptg_string(1,8,ptv_str_lang), ...
          'Menubar',ptv_fig_menubar,...
          'Tag','ptt_simul_param',...
          'position',[60 40 565 560]);

% Clolourful effect
ptf_cfbcg(gcf,ptv_cfbcg)

%------ PID param ------------
 HT1_PID = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',[1 0.5 0],... 	
          'Position',[20 520 240 25],...
          'String',ptg_string(2,4,ptv_str_lang));
      
HT2_Z_R =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 490 160 25],...
          'String',ptg_string(8,10,ptv_str_lang));

Qz_r =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qz_r),...
          'Position',[182 490 80 25],...
          'CallBack',['ic(1,11)=1;Qz_r = str2num(get(gco,''String''));']);

if(t_i<1.000e9)
QT_I_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 460 160 25],...
          'String',ptg_string(8,11,ptv_str_lang));

Qt_i =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qt_i),...
          'Position',[182 460 80 25],...
          'CallBack',['ic(1,12)=1;Qt_i = str2num(get(gco,''String''));']);
end

if(t_d~=0)
QT_D_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 430 160 25],...
          'String',ptg_string(8,12,ptv_str_lang)); 

Qt_d =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qt_d),...
          'Position',[182 430 80 25],...
          'CallBack',['ic(1,13)=1;Qt_d = str2num(get(gco,''String''));']);
end

%------ T_R pre ANTI-RESET WIND UP ---------
%
if(t_i<1.000e9)
QT_R_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 400 160 25],...
          'String',ptg_string(8,13,ptv_str_lang)); 
Qt_r =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qt_r),...
          'Position',[182 400 80 25],...
          'CallBack',['ic(1,20)=1;Qt_r = str2num(get(gco,''String''));']);
end

%------ T_F pre filtrovanie T_D ---------
%

if(t_d > 0)
    
QT_F_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 370 160 25],...
          'String',ptg_string(8,59,ptv_str_lang));
Qt_f =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qt_f),...
          'Position',[182 370 80 25],...
          'CallBack',['ic(1,22)=1;Qt_f = str2num(get(gco,''String''));']);
end

%------ Koniec - PID param ------------
      
%--------------------- regulovany prenos ------------------------------------ 
QG_text0 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',[0.5 0.9 0.67],... 	
          'Position',[300 490 240 25],...
          'String',ptg_string(2,5,ptv_str_lang));

%----------------------------- cit ------------------------------------------                   
                    
       Qcit_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[300 460 60 25],...
          'String',ptg_string(8,14,ptv_str_lang));
       Qcit =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qcit),...
          'Position',[360 460 180 25],...
          'CallBack',['ic(1,14)=1;Qcit=str2num(get(gco,''String''));']);

%------------------------------- men ----------------------------------------          
          
       Qmen_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[300 430 60 25],...
          'String',ptg_string(8,15,ptv_str_lang));
       Qmen =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qmen) ,...
          'Position',[360 430 180 25],...
          'CallBack',['ic(1,15)=1;Qmen=str2num(get(gco,''String''));']);
      
%------------------------------ Dr ---------------------------------------

QD_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[300 400 60 25],...
          'String',ptg_string(8,4,ptv_str_lang));
QDr =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(QDr),...
          'Position',[360 400 180 25],...
          'CallBack',['ic(1,16)=1;QDr=str2num(get(gco,''String''));']);

%---- ZISKAT PRENOS -----%
prenos = uicontrol(gcf,...
          'Style','push',...
          'Position',[300 370 240 25],...
          'Fontsize',[12],...
          'Fontweight','bold',...
          'String',ptg_string(3,11,ptv_str_lang),...
          'ForegroundColor','black',... 
          'CallBack','close,ziskat_gs;');
%--------------------- Koniec - regulovany prenos ----------------------------

%--------------------- ziadana velicina w(t) ------------------------------------ 
 QW_text0 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor','yellow',... 	
          'Position',[20 325 240 25],...
          'String',ptg_string(2,6,ptv_str_lang));

% W_povodna      

QW_povodna_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[20 295 160 25],...
          'String',ptg_string(8,16,ptv_str_lang));

QW_povodna =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(QW_povodna),...
          'Position',[182 295 80 25],...
          'CallBack',['ic(1,1)=1;QW_povodna=str2num(get(gco,''String''));']);

% W_nova

QW_nova_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[20 265 160 25],...
          'String',ptg_string(8,17,ptv_str_lang));

QW_nova =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(QW_nova),...
          'Position',[182 265 80 25],...
          'CallBack',['ic(1,2)=1;QW_nova=str2num(get(gco,''String''));']);

% W_cas_zmeny

QW_cas_zmeny_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[20 235 160 25],...
          'String',ptg_string(8,18,ptv_str_lang));

QW_cas_zmeny =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(QW_cas_zmeny),...
          'Position',[182 235 80 25],...
          'CallBack',['ic(1,3)=1;QW_cas_zmeny=str2num(get(gco,''String''));']);

%--------------------- poruchova velicina r(t) ------------------------------------ 

 QR_text0 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',[1 0.25 0.1],... 	
          'Position',[300 325 240 25],...
          'String',ptg_string(2,7,ptv_str_lang));

% R_povodna      

QR_povodna_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[300 295 160 25],...
          'String',ptg_string(8,19,ptv_str_lang));

QR_povodna =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(QR_povodna),...
          'Position',[462 295 80 25],...
          'CallBack',['ic(1,4)=1;QR_povodna=str2num(get(gco,''String''));']);

% R_nova

QR_nova_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[300 265 160 25],...
          'String',ptg_string(8,20,ptv_str_lang));

 QR_nova =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(QR_nova),...
          'Position',[462 265 80 25],...
          'CallBack',['ic(1,5)=1;QR_nova=str2num(get(gco,''String''));']);

% R_cas_zmeny

 QR_cas_zmeny_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[300 235 160 25],...
          'String',ptg_string(8,21,ptv_str_lang));

QR_cas_zmeny =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(R_cas_zmeny),...
          'Position',[462 235 80 25],...
          'CallBack',['ic(1,6)=1;QR_cas_zmeny=str2num(get(gco,''String''));']);

%-----

QP_text0 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',[0.2 0.8 0.2],... 	
          'Position',[20 185 240 25],...
          'String',ptg_string(2,8,ptv_str_lang));

%------------ Parametre simul�cie ------------------------------------

QP_text0 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',[0.2 0.8 0.2],... 	
          'Position',[20 185 240 25],...
          'String',ptg_string(2,8,ptv_str_lang));

%--------------------- b_w ---------------------------------- 

Qb_w_text =  uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontsize',[12],...
          'Fontweight','bold',...
          'BackgroundColor',fgcolor,... 	
          'Position',[20 155 160 25],...
          'String',ptg_string(8,58,ptv_str_lang));

Qb_w2 =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 	
          'Fontsize',[11],...
          'String',num2str(Qb_w),...
          'Position',[182 155 80 25],...
          'CallBack',['ic(1,21)=1;Qb_w=str2num(get(gco,''String''));']);

%--------------------- presnost_riadenia ---------------------------------- 

Qpresnost_riadenia_text =  uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontsize',[12],...
          'Fontweight','bold',...
          'BackgroundColor',fgcolor,... 	
          'Position',[20 120 160 25],...
          'String',ptg_string(8,22,ptv_str_lang));

Qpresnost_riadenia =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 	
          'Fontsize',[11],...
          'String',num2str(Qpresnost_riadenia),...
          'Position',[182 120 80 25],...
          'CallBack',['ic(1,7)=1;Qpresnost_riadenia=str2num(get(gco,''String''));']);

%--------------------- cas_simulacie -------------------------------------- 

Qcas_simulacie_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[20 85 160 25],...
          'String',ptg_string(8,23,ptv_str_lang));

Qcas_simulacie =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qcas_simulacie),...
          'Position',[182 85 80 25],...
          'CallBack',['ic(1,8)=1;Qcas_simulacie=str2num(get(gco,''String''));']);

%------------------ U_dolne_obmedzenie ------------------------- 

QU_dolne_obmedzenie_text =  uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[20 50 160 25],...
          'String',ptg_string(8,24,ptv_str_lang));

QU_dolne_obmedzenie =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String', num2str(QU_dolne_obmedzenie),...
          'Position',[182 50 80 25],...
          'CallBack',['ic(1,9)=1;QU_dolne_obmedzenie=str2num(get(gco,''String''));']);

%-------------------- U_horne_obmedzenie ----------------------- 

QU_horne_obmedzenie_text =  uicontrol(gcf,...
          'Style','text',...;
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[20 15 160 25],...
          'String',ptg_string(8,25,ptv_str_lang));

QU_horne_obmedzenie=  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QU_horne_obmedzenie),...
          'Position',[182 15 80 25],...
          'CallBack',['ic(1,10)=1;QU_horne_obmedzenie=str2num(get(gco,''String''));']);

      
%--------------------- Konstanty kriterii kvality ------------------------------------ 

QIKK_text0 = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',[1 0.5 0.25],... 	
          'Position',[300 185 240 25],...
          'String',ptg_string(2,9,ptv_str_lang));

% Q_u pre ISE_u
Qq_u_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[300 155 160 25],...
          'String',ptg_string(8,26,ptv_str_lang));
 Qq_u2 =  uicontrol(gcf,...1
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(Qq_u),...
          'Position',[462 155 80 25],...
          'CallBack',['ic(1,17)=1;Qq_u=str2num(get(gco,''String''));']);

% Q_du pre ISE_du

 Q_du_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[300 120 160 25],...
          'String',ptg_string(8,27,ptv_str_lang));

Q_du2 =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(Qq_du),...
          'Position',[462 120 80 25],...
          'CallBack',['ic(1,18)=1;Qq_du=str2num(get(gco,''String''));']);

% Qq_de pre ISE_de      
    Qq_de_text = uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'BackgroundColor',fgcolor,... 	
          'Position',[300 85 160 25],...
          'String',ptg_string(8,28,ptv_str_lang));
    Qq_de2 =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],... 
          'Fontsize',[11],...
          'String',num2str(Qq_de),...
          'Position',[462 85 80 25],...
          'CallBack',['ic(1,19)=1;Qq_de=str2num(get(gco,''String''));']);
      

%----SPAT-----%
navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[300 15 60 25],...
          'Fontweight','bold',...
          'Fontsize',[12],...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,if(J1==1),J2=2;zatv,else,reg_v,end');



%----SIMULACIA-----%
      
navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[400 15 150 25],...
          'Fontsize',[12],...
          'Fontweight','bold',...
          'String',ptg_string(3,10,ptv_str_lang),...
          'ForegroundColor','black',... 
          'BackgroundColor',[0.64 0.82 0.02],... 
          'CallBack','close,testsim;');
end