% SUS2
% Parametre pre aperiodicku PCH
% Volane z - SUS



Qu_0=u_0;
Qu_nek=u_nek;
Qy_0=y_0;
Qy_nek=y_nek;
Qt0=t0;
Qt_D=t_D;
Qt1=t1;
Qt2=t2;
Qcas_simulacie =cas_simulacie;

%---------- modre prekrytie
Qtext =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',get(gcf,'Color'),...
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 290 180 50],...
  'String','');

%-------hodnota u_0 ---------- 

Qu_0_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],...
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 265 120 20],...
  'String',ptg_string(8,29,ptv_str_lang));

Qu_0 =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'String',num2str(Qu_0),...
  'Position',[120 265 80 20],...
  'CallBack',['ic(1,1)=1;Qu_0=str2num(get(gco,''String''));']);

%-------hodnota u_nek ---------- 

Qu_nek_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],... 
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 240 120 20],...
  'String',ptg_string(8,30,ptv_str_lang));

Qu_nek =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'String',num2str(Qu_nek),...
  'Position',[120 240 80 20],...
  'CallBack',['ic(1,2)=1;Qu_nek=str2num(get(gco,''String''));']);


%-------hodnota y_0 ---------- 

Qy_0_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],... 
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 215 120 20],...
  'String',ptg_string(8,31,ptv_str_lang));

Qy_0 =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'String', num2str(Qy_0),...
  'Position',[120 215 80 20],...
  'CallBack',['ic(1,3)=1;Qy_0=str2num(get(gco,''String''));']);


%-------hodnota y_nek ---------- 

Qy_nek_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],... 
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 190 120 20],...
  'String',ptg_string(8,34,ptv_str_lang));

Qy_nek =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'String',num2str(Qy_nek),...
  'Position',[120 190 80 20],...
  'CallBack',['ic(1,4)=1;Qy_nek=str2num(get(gco,''String''));']);

%------------hodnota t0 --------

Qt0_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],... 	
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 165 120 20],...
  'String',ptg_string(8,35,ptv_str_lang));

Qt0 =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'String',num2str(Qt0),...
  'Position',[120 165 80 20],...
  'CallBack',['ic(1,5)=1;Qt0=str2num(get(gco,''String''));']);
  
%------------hodnota t_D --------

Qt0_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],... 	
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 140 120 20],...
  'String',ptg_string(8,38,ptv_str_lang));

Qt_D =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'String',num2str(Qt_D),...
  'Position',[120 140 80 20],...
  'CallBack',['ic(1,6)=1;Qt_D=str2num(get(gco,''String''));']);
  
%-------hodnota t1 ---------- 
Qt1_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],...
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 115 120 20],...
  'String',ptg_string(8,36,ptv_str_lang));

Qt1 =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'String',num2str(Qt1),...
  'Position',[120 115 80 20],...
  'CallBack',['ic(1,7)=1;Qt1=str2num(get(gco,''String''));']);
  

%-------hodnota t2 ---------- 
Qt2_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],... 	
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 90 120 20],...
  'String',ptg_string(8,37,ptv_str_lang));

Qt2 =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'String', num2str(Qt2),...
  'Position',[120 90 80 20],...
  'CallBack',['ic(1,8)=1;Qt2=str2num(get(gco,''String''));']);

%------- cas_simulacie ---------- 
Qcas_simulacie_text =  uicontrol(gcf,...
  'Style','text',...
  'ForegroundColor','black',...
  'BackgroundColor',[fgcolor],... 	
  'Fontweight','bold',...
  'Fontsize',[12],...
  'Position',[20 65 120 20],...
  'String',ptg_string(8,23,ptv_str_lang));

Qcas_simulacie =  uicontrol(gcf,...
  'Style','edit',...
  'ForegroundColor','black',...
  'Fontsize',[12],...
  'BackgroundColor',[1 1 1],... 	
  'Fontsize',[12],...
  'String', num2str(Qcas_simulacie),...
  'Position',[120 65 80 20],...
  'CallBack',['ic(1,9)=1;Qcas_simulacie=str2num(get(gco,''String''));']);

% identifikacia prveho radu
n=1;

% ilustracny graf
ptg_ilustr_plot