% SUSTAVY
%
%   Dava na vyber typ identifikacie:
%
%   SUSTAVA 1.RADU - PARAM
%   SUSTAVA VYSSIEHO RADU - PARAM2
%   SPAT - SUS



figure('Color','blue',...
             'Resize','off',...
             'Numbertitle','off',...
             'Menubar',ptv_fig_menubar,...
             'Name',ptg_string(1,3,ptv_str_lang),...
             'position',[35 120 240 150]);

% Clolourful effect
ptf_cfbcg(gcf,ptv_cfbcg)
%-------------------------------------------------------------------
  
pth_but1 = uicontrol(gcf,...
  'Style','push',...
  'Position',[30 100 180 30],...
  'String',ptg_string(3,15,ptv_str_lang),...
  'Fontsize',[11],...
  'Fontweight','bold',...
  'ForegroundColor','black',...
  'CallBack','close,param');

pth_but2 = uicontrol(gcf,...
  'Style','push',...
  'Position',[30 60 180 30],...
  'String',ptg_string(3,16,ptv_str_lang),...
  'Fontsize',[11],...  
  'Fontweight','bold',...
  'ForegroundColor','black',...
  'CallBack','close,param2');

pth_but3 = uicontrol(gcf,...
  'Style','push',...
  'Position',[30 15 60 25],...
  'String',ptg_string(3,2,ptv_str_lang),...
  'Fontsize',[11],...
  'Fontweight','bold',...
  'ForegroundColor','black',...
  'CallBack','close,sus');