% TESTZ
% Testuje v FILTRACIA
% ci si filter vyzaduje zadanie parametra zvlnenie r


if(typfil(1)>2)
       if(typfil(1)==3)
           Qzvlnenie=0.5;
       elseif(typfil(1)==4)
           Qzvlnenie=20;
       elseif(typfil(1)==5)
           Qzvlnenie=[0.5 20];
       end
       zvlnenie=Qzvlnenie;
       
       zvlnenie_text =  uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...		
          'Position',[20 85 100 25],...
          'String',ptg_string(8,50,ptv_str_lang));
       Qzvlnenie =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Fontsize',[11],...
          'String',num2str(Qzvlnenie),...
          'Position',[120 85 100 25],...
          'CallBack',['ic(1,3)=1;Qzvlnenie=str2num(get(Qzvlnenie,''String''));']);
  else
      zvlnenie_text =  uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor','blue',... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...		
          'Position',[20 85 200 25],...
          'String','');
  end