% TESTZ
% Testuje v FILTRACIA
% ci si filter vyzaduje zadanie parametra zvlnenie r

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------

if(typfil(1)>2)
       if(typfil(1)==3)
           Qzvlnenie=0.5;
       elseif(typfil(1)==4)
           Qzvlnenie=20;
       elseif(typfil(1)==5)
           Qzvlnenie=[0.5 20];
       end
       zvlnenie=Qzvlnenie;
       
       zvlnenie_text =  uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...		
          'Position',[20 85 100 25],...
          'String',ptg_string(8,50,ptv_str_lang));
       Qzvlnenie =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'BackgroundColor',[1 1 1],...
          'HorizontalAlignment','center',...
          'Fontsize',[11],...
          'String',num2str(Qzvlnenie),...
          'Position',[120 85 100 25],...
          'CallBack',['ic(1,3)=1;Qzvlnenie=str2num(get(Qzvlnenie,''String''));']);
  else
      zvlnenie_text =  uicontrol(gcf,...
          'Style','text',...
          'ForegroundColor','black',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor','blue',... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...		
          'Position',[20 85 200 25],...
          'String','');
  end