% VYB_IDENT
%
%   Vyber metody identifikacie
%
%   Dava na vyber:
%
%   IDENTIFIKACIA Z VLASTNYCH PARAMETROV - SUS
%   IDENTIFIKACIA Z DATOVEHO SUBORU - CITSUB
%   IDENTIFIKACIA Z MODELU - NA_MODEL

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


% Vycistit pamat z ladenia pomocou ID_TUNE
%
clear y_backup

pth_fig = figure('Color','blue',...
          'Tag','ptt_vyb_ident',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,3,ptv_str_lang), ...
          'Position',[120 200 360 140]);

% Clolourful effect
ptf_cfbcg(gcf,ptv_cfbcg)

pth_but1 = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 95 300 30],...
          'String',ptg_string(3,12,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,sus');

pth_but2 = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 55 300 30],...
          'String',ptg_string(3,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','citsub');

pth_but3 = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 300 30],...
          'String',ptg_string(3,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,na_model');
