% VYB_FIL
%
%   Vyber FILTRACIE alebo IDENTIFIKACIE
%
%   Dava na vyber:
%
%   FILTRACIA - FILTRACIA
%   IDENTIFIKACIA - ID_PARMETRE , premenna yn=ynew, aby mohla prebehnut
%   identifikacia podla Strejca
%   SPAT - NORMALIZIACIA



typ_i = 0;

figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,13,ptv_str_lang), ...
          'Position',[120 200 300 100]);

Qtyp_i=uicontrol(gcf,'Tag','KM',...
    'Style','Check','Units','Pixels','Position',[160 20 130 20],...
    'ForegroundColor','Black',...
    'Tag','ptt_periodic',...
    'BackgroundColor',fgcolor,...  
    'Fontweight','bold',...
    'String',ptg_string(5,3,ptv_str_lang),...
    'Value',typ_i,...
    'Callback','typ_i=get(gco,''Value'')+1;');

sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[15 55 130 30],...
          'String',ptg_string(3,20,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','red',...
          'CallBack','close,close(findobj(''Tag'',''ptt_plot'')),filtracia');

sposob_navrhu2= uicontrol(gcf,...
          'Style','push',...
          'Position',[160 55 130 30],...
          'String',ptg_string(3,4,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','red',...
          'CallBack','close(findobj(''Tag'',''ptt_plot'')),naspat=''close,vyb_fil'';typ_i=get(findobj(''Tag'',''ptt_periodic''),''Value'')+1;close,if(typ_i==1),id_parametre,else,[OK,K,T_km,ksi_km,D_km] = km_id(t,yn,naspat);ic2=0;param_km,end');

navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[15 15 60 30],...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,close(findobj(''Tag'',''ptt_plot'')),normalizacia');