% VYB_IDENT
%
%   Vyber metody identifikacie
%
%   Dava na vyber:
%
%   IDENTIFIKACIA Z VLASTNYCH PARAMETROV - SUS
%   IDENTIFIKACIA Z DATOVEHO SUBORU - CITSUB
%   IDENTIFIKACIA Z MODELU - NA_MODEL



% Vycistit pamat z ladenia pomocou ID_TUNE
%
clear y_backup

pth_fig = figure('Color','blue',...
          'Tag','ptt_vyb_ident',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,3,ptv_str_lang), ...
          'Position',[120 200 360 140]);

% Clolourful effect
ptf_cfbcg(gcf,ptv_cfbcg)

pth_but1 = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 95 300 30],...
          'String',ptg_string(3,12,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,sus');

pth_but2 = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 55 300 30],...
          'String',ptg_string(3,13,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','citsub');

pth_but3 = uicontrol(gcf,...
          'Style','push',...
          'Position',[30 15 300 30],...
          'String',ptg_string(3,14,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','black',...
          'CallBack','close,na_model');
