% VYB_FIL
%
%   Vyber FILTRACIE alebo IDENTIFIKACIE
%
%   Dava na vyber:
%
%   FILTRACIA - FILTRACIA
%   IDENTIFIKACIA - ID_PARMETRE , premenna yn=ynew, aby mohla prebehnut
%   identifikacia podla Strejca
%   SPAT - NORMALIZIACIA

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


typ_i = 0;

figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'Menubar',ptv_fig_menubar,...
          'Name',ptg_string(1,13,ptv_str_lang), ...
          'Position',[120 200 300 100]);

Qtyp_i=uicontrol(gcf,'Tag','KM',...
    'Style','Check','Units','Pixels','Position',[160 20 130 20],...
    'ForegroundColor','Black',...
    'Tag','ptt_periodic',...
    'BackgroundColor',fgcolor,...  
    'Fontweight','bold',...
    'String',ptg_string(5,3,ptv_str_lang),...
    'Value',typ_i,...
    'Callback','typ_i=get(gco,''Value'')+1;');

sposob_navrhu= uicontrol(gcf,...
          'Style','push',...
          'Position',[15 55 130 30],...
          'String',ptg_string(3,20,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','red',...
          'CallBack','close,close(findobj(''Tag'',''ptt_plot'')),filtracia');

sposob_navrhu2= uicontrol(gcf,...
          'Style','push',...
          'Position',[160 55 130 30],...
          'String',ptg_string(3,4,ptv_str_lang),...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'ForegroundColor','red',...
          'CallBack','close(findobj(''Tag'',''ptt_plot'')),naspat=''close,vyb_fil'';typ_i=get(findobj(''Tag'',''ptt_periodic''),''Value'')+1;close,if(typ_i==1),id_parametre,else,[OK,K,T_km,ksi_km,D_km] = km_id(t,yn,naspat);ic2=0;param_km,end');

navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[15 15 60 30],...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'Callback','close,close(findobj(''Tag'',''ptt_plot'')),normalizacia');