% ZISKAT_GS2
%
%   Volane zo - ZISKAT_GS
%   pre Strejcov tvar



Qnn=nn;
QKK=KK;
QTT=TT;

%----------------------------- n ------------------------------------------                   
                    
       Qn_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 160 80 25],...
          'String',ptg_string(8,1,ptv_str_lang));
      
       Qnn =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qnn),...
          'Position',[102 160 80 25],...
          'CallBack',['ic(1,1)=1;Qnn=str2num(get(gco,''String''));']);
      
%------------------------------- K ----------------------------------------          
          
       QK_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 125 80 25],...
          'String',ptg_string(8,2,ptv_str_lang));
      
       QKK =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QKK) ,...
          'Position',[102 125 80 25],...
          'CallBack',['ic(1,2)=1;QKK=str2num(get(gco,''String''));']);
 
          
 %------------------------------- T ---------------------------------------         
          
       QT_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 90 80 25],...
          'String',ptg_string(8,3,ptv_str_lang));
      
       QTT =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QTT),...
          'Position',[102 90 80 25],...
          'CallBack',['ic(1,3)=1;QTT=str2num(get(gco,''String''));']);              