% ZISKAT_GS
%
%   Ziskaju sa parametre regulovaneho prenosu G(s)
%
%   Zadaju sa parametre Strejcovho prenosu regulovaneho systemu
%
%   Dava na vyber:
%
%   VYPOCITAT - prebehne vypocet a potom sa spusti SIMUL_PARAM
%   SPAT - SIMUL_PARAM

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


% ic je vektor na kontrolu zadania vstupov
ic=zeros(1,3);

% Prednastavene parametre pre Strejcov prenos:
nn=n;
KK=K;
TT=T;

TT_km=T_km;
kksi_km=ksi_km;

figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'name',ptg_string(1,5,ptv_str_lang), ...
          'Menubar',ptv_fig_menubar,...
          'position',[150 100 240 270]);

% Clolourful effect
ptf_cfbcg(gcf,ptv_cfbcg)

%----- Info -----%

       Qn2_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor','yellow',... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[15 200 210 65],...
          'String',ptg_string(2,5,ptv_str_lang));

%--- Vyber ---
if(typ_id>2)
    typ_id=1;
end
      typid = uicontrol(gcf,...
          'Style','popup',...
          'Position',[20 190 200 35],...
          'String',ptg_string(4,1,ptv_str_lang),...
          'Value',typ_i,...
          'ForegroundColor','black',...
          'BackGroundColor','white',...
          'CallBack','typ_i = get(gco,''Value'');if(typ_i)==1,ziskat_gs2,elseif(typ_i)==2,ziskat_gs3,end;');

%----SPAT-----%

navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[20 10 60 25],...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'CallBack','close,simul_param');
      
%----------%   
navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[102 10 120 25],...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'String',ptg_string(3,1,ptv_str_lang),...
          'ForegroundColor','red',...
          'CallBack','close,if(typ_i==1),test_gs,else,test_gs2,end');

if(typ_i)==1       % Strejcov tvar
    ziskat_gs2
elseif(typ_i)==2   % Kmitavy tvar
    ziskat_gs3
end  