% ZISKAT_GS2
%
%   Volane zo - ZISKAT_GS
%   pre Strejcov tvar

% Copyright is with the following author(s):
%
% (c) 2012 Juraj Oravec, Slovak University of Technology in Bratislava,
% juraj.oravec@stuba.sk
% (c) 2012 Monika Bakosova, Slovak University of Technology in Bratislava,
% monika.bakosova@stuba.sk
% ------------------------------------------------------------------------------
% Legal note:
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public
% License as published by the Free Software Foundation; either
% version 2.1 of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
% General Public License for more details.
%
% You should have received a copy of the GNU General Public
% License along with this library; if not, write to the
% Free Software Foundation, Inc.,
% 59 Temple Place, Suite 330,
% Boston, MA 02111-1307 USA
%
% ------------------------------------------------------------------------------


Qnn=nn;
QKK=KK;
QTT=TT;

%----------------------------- n ------------------------------------------                   
                    
       Qn_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 160 80 25],...
          'String',ptg_string(8,1,ptv_str_lang));
      
       Qnn =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(Qnn),...
          'Position',[102 160 80 25],...
          'CallBack',['ic(1,1)=1;Qnn=str2num(get(gco,''String''));']);
      
%------------------------------- K ----------------------------------------          
          
       QK_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 125 80 25],...
          'String',ptg_string(8,2,ptv_str_lang));
      
       QKK =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QKK) ,...
          'Position',[102 125 80 25],...
          'CallBack',['ic(1,2)=1;QKK=str2num(get(gco,''String''));']);
 
          
 %------------------------------- T ---------------------------------------         
          
       QT_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor',[fgcolor],... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[20 90 80 25],...
          'String',ptg_string(8,3,ptv_str_lang));
      
       QTT =  uicontrol(gcf,...
          'Style','edit',...
          'ForegroundColor','black',...
          'Fontsize',[11],...
          'BackgroundColor',[1 1 1],... 	
          'String',num2str(QTT),...
          'Position',[102 90 80 25],...
          'CallBack',['ic(1,3)=1;QTT=str2num(get(gco,''String''));']);              