% ZISKAT_GS
%
%   Ziskaju sa parametre regulovaneho prenosu G(s)
%
%   Zadaju sa parametre Strejcovho prenosu regulovaneho systemu
%
%   Dava na vyber:
%
%   VYPOCITAT - prebehne vypocet a potom sa spusti SIMUL_PARAM
%   SPAT - SIMUL_PARAM



% ic je vektor na kontrolu zadania vstupov
ic=zeros(1,3);

% Prednastavene parametre pre Strejcov prenos:
nn=n;
KK=K;
TT=T;

TT_km=T_km;
kksi_km=ksi_km;

figure('Color','blue',...
          'Resize','off',...
          'Numbertitle','off',...
          'name',ptg_string(1,5,ptv_str_lang), ...
          'Menubar',ptv_fig_menubar,...
          'position',[150 100 240 270]);

% Clolourful effect
ptf_cfbcg(gcf,ptv_cfbcg)

%----- Info -----%

       Qn2_text =  uicontrol(gcf,...
          'Style','text',...
          'Fontsize',[12],...
          'ForegroundColor','black',...
          'BackgroundColor','yellow',... 
          'Fontweight','bold',...
          'HorizontalAlignment','center',...
          'Position',[15 200 210 65],...
          'String',ptg_string(2,5,ptv_str_lang));

%--- Vyber ---
if(typ_id>2)
    typ_id=1;
end
      typid = uicontrol(gcf,...
          'Style','popup',...
          'Position',[20 190 200 35],...
          'String',ptg_string(4,1,ptv_str_lang),...
          'Value',typ_i,...
          'ForegroundColor','black',...
          'BackGroundColor','white',...
          'CallBack','typ_i = get(gco,''Value'');if(typ_i)==1,ziskat_gs2,elseif(typ_i)==2,ziskat_gs3,end;');

%----SPAT-----%

navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[20 10 60 25],...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'String',ptg_string(3,2,ptv_str_lang),...
          'ForegroundColor','black',...
          'CallBack','close,simul_param');
      
%----------%   
navrat = uicontrol(gcf,...
          'Style','push',...
          'Position',[102 10 120 25],...
          'Fontsize',[11],...
          'Fontweight','bold',...
          'String',ptg_string(3,1,ptv_str_lang),...
          'ForegroundColor','red',...
          'CallBack','close,if(typ_i==1),test_gs,else,test_gs2,end');

if(typ_i)==1       % Strejcov tvar
    ziskat_gs2
elseif(typ_i)==2   % Kmitavy tvar
    ziskat_gs3
end  